# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"

  - package-ecosystem: "npm"
    directory: "/"
    patterns:
      - "@types/node"
    multi-ecosystem-group: "node"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/.devcontainer"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
      - dependency-name: "devcontainers/typescript-node"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/.devcontainer"
    patterns:
      - "node"
      - "devcontainers/typescript-node"
    multi-ecosystem-group: "node"
  
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

multi-ecosystem-groups:
  node:
    schedule:
      interval: "weekly"
