# Workflow for testing that the code of incoming pull requests builds, validates, and follows style guidelines

name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency: 
  group: pr-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_NODE_VERSION: 24.19

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.BUILD_NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Run check
        run: npm run check
      - name: Run linter
        run: npm run lint

  test:
    name: Tests
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.BUILD_NODE_VERSION }}
          cache: npm

      - name: Playwright browser cache
        uses: actions/cache@v6
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browser dependencies
        run: npx playwright install-deps chromium
      - name: Install Playwright browsers
        run: npx playwright install chromium

      # Cache .cache so image transforms don't take forever
      # Need to be after npm ci since that clears node_modules
      - name: Build cache
        id: build-cache
        uses: actions/cache@v6
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-integration-build-cache

      # Pre-build so transforms are cached
      - name: Build server
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit
      - name: Run E2E tests
        run: npm run test:e2e

  build:
    name: Build
    needs:
      - test
    runs-on: ubuntu-latest
    env:
      IMAGE_FULL_NAME: ${{ vars.REGISTRY_HOST || 'ghcr.io' }}/${{ vars.IMAGE_NAME || github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_FULL_NAME }}
          tags: |
            type=raw,value=pr
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image
        id: image
        uses: docker/build-push-action@v7
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: false
          sbom: false
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
